apps:
  - name: 'paradb-api'
    script: './node_modules/.bin/ts-node -r tsconfig-paths/register ./src/index.ts'
    max_restarts: 3
    restart_delay: 2000
    min_uptime: 10000
    # Show timestamps in logs
    log_date_format: 'YYYY-MM-DD HH:mm Z'
