module.exports = {
  esbuild: {
    platform: 'node',
    // For some reason, the sourceRoot generated by esbuild is ${workspaceFolder}/src, leading to a double "src" folder
    // (e.g. ${workspaceFolder}/src/src/index.ts).
    // Manually override it to strip the extra /src.
    sourceRoot: '../',
    external: ['./node_modules/*']
  }
}
